[features]
seeds = false

[programs.localnet]
solana_kontent = "8rDWSauWEjKVZ6bKM1s8DrTtuLsqj2Eo3xSqUx9RvtfY"

[programs.devnet]
solana_twitter = "8rDWSauWEjKVZ6bKM1s8DrTtuLsqj2Eo3xSqUx9RvtfY"

[programs.mainnet]
solana_twitter = "8rDWSauWEjKVZ6bKM1s8DrTtuLsqj2Eo3xSqUx9RvtfY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/radimersky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
